//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaProtesta
    {
        public int CategoriaProtestaID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> EstatusID { get; set; }
        public int AuditoriaID { get; set; }
    }
}
