//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companias()
        {
            this.Miembros = new HashSet<Miembros>();
        }
    
        public int CompaniaID { get; set; }
        public string nombre { get; set; }
        public int BatallonID { get; set; }
        public string codAnterior { get; set; }
        public int Nomina { get; set; }
        public int TenienteGeneral { get; set; }
        public int MayorGeneral { get; set; }
        public int General { get; set; }
        public int Coronel { get; set; }
        public int TenienteCoronel { get; set; }
        public int Mayor { get; set; }
        public int Capitan { get; set; }
        public int PrimerTeniente { get; set; }
        public int SeguntoTeniente { get; set; }
        public int Cadete4toAño { get; set; }
        public int Cadete3erAño { get; set; }
        public int Cadete2doAño { get; set; }
        public int Cadete1erAño { get; set; }
        public int AspiranteAcadete { get; set; }
        public int SargentoMayor { get; set; }
        public int SargentoAyC { get; set; }
        public int Sargento { get; set; }
        public int Cabo { get; set; }
        public int Raso { get; set; }
        public int Conscripto { get; set; }
        public int Asimilado { get; set; }
        public int Igualado { get; set; }
        public bool Historica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miembros> Miembros { get; set; }
    }
}
