//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoNovedades
    {
        public int NovedadesID { get; set; }
        public int TipoNovedadID { get; set; }
        public System.DateTime FechaNovedad { get; set; }
        public System.TimeSpan HoraNovedad { get; set; }
        public int AuditoriaID { get; set; }
        public int TipoID { get; set; }
        public int ProvinciaID { get; set; }
    }
}
