//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextDbERD : DbContext
    {
        public ContextDbERD()
            : base("name=ContextDbERD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Regiones> Regiones { get; set; }
        public virtual DbSet<Sectores> Sectores { get; set; }
        public virtual DbSet<Batallones> Batallones { get; set; }
        public virtual DbSet<Rangos> Rangos { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<Companias> Companias { get; set; }
        public virtual DbSet<Instituciones> Instituciones { get; set; }
        public virtual DbSet<Miembros> Miembros { get; set; }
    }
}
