//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipios
    {
        public int MunicipioID { get; set; }
        public string nombre { get; set; }
        public int ProvinciaID { get; set; }
        public string codAnterior { get; set; }
    
        public virtual Provincias Provincias { get; set; }
    }
}
