//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class NovedadRepatriaciones
    {
        public int NovedadRepatriacionID { get; set; }
        public int TipoNovedadID { get; set; }
        public int PaisID { get; set; }
        public int ProvinciaID { get; set; }
        public int Cantidad { get; set; }
        public int SexoID { get; set; }
        public int BrigadaID { get; set; }
        public int EstatusID { get; set; }
        public string Causa { get; set; }
        public System.TimeSpan HoraNovedad { get; set; }
        public System.DateTime FechaNovedad { get; set; }
        public int AuditoriaID { get; set; }
        public int CausaID { get; set; }
    
        public virtual TipoNovedad TipoNovedad { get; set; }
    }
}
