//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class NovedadIncautacion
    {
        public int NovedadIncautacionID { get; set; }
        public int TipoIncautacionID { get; set; }
        public int TipoNovedadID { get; set; }
        public decimal Cantidad { get; set; }
        public int TipoMedidaID { get; set; }
        public int ProductoID { get; set; }
        public System.DateTime FechaNovedad { get; set; }
        public System.TimeSpan HoraNovedad { get; set; }
        public int ProvinciaID { get; set; }
        public int BrigadaID { get; set; }
        public string Causa { get; set; }
        public int EstatusID { get; set; }
        public int AuditoriaID { get; set; }
    
        public virtual Auditoria Auditoria { get; set; }
        public virtual Estatus Estatus { get; set; }
    }
}
