//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class NovedadProtesta
    {
        public int NovedadProtestaID { get; set; }
        public int TipoNovedadID { get; set; }
        public int ProvinciaID { get; set; }
        public System.DateTime FechaNovedad { get; set; }
        public Nullable<System.TimeSpan> HoraNovedad { get; set; }
        public int AuditoriaID { get; set; }
        public int EstatusID { get; set; }
        public string LugarProtesta { get; set; }
        public int TipoProtestaID { get; set; }
        public int InstitucionProtestanteID { get; set; }
        public int CategoriaProtestaID { get; set; }
        public string Causa { get; set; }
    }
}
