//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class NovedadProtesta
    {
        public int NovedadProtestaID { get; set; }
        public int TipoNovedadID { get; set; }
        public int ProvinciaID { get; set; }
        public System.DateTime FechaNovedad { get; set; }
        public Nullable<System.TimeSpan> HoraNovedad { get; set; }
        public int AuditoriaID { get; set; }
        public int EstatusID { get; set; }
        public string LugarProtesta { get; set; }
        public int TipoProtestaID { get; set; }
        public int InstitucionProtestanteID { get; set; }
        public int CategoriaProtestaID { get; set; }
        public string Causa { get; set; }
    }
}
