//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class NovedadMuertes
    {
        public int NovedadMuerteID { get; set; }
        public int TipoNovedadID { get; set; }
        public int ProvinciaID { get; set; }
        public System.DateTime FechaNovedad { get; set; }
        public System.TimeSpan HoraNovedad { get; set; }
        public int AuditoriaID { get; set; }
        public int EstatusID { get; set; }
        public int RangoID { get; set; }
        public int SexoID { get; set; }
        public string Causa { get; set; }
        public int TipoMuerteID { get; set; }
        public int BrigadaID { get; set; }
        public int CompaniaID { get; set; }
        public int TipoMiembroID { get; set; }
    }
}
