//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rangos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rangos()
        {
            this.Miembros = new HashSet<Miembros>();
        }
    
        public int RangoID { get; set; }
        public string nombre { get; set; }
        public int nivelRangoID { get; set; }
        public string Imagen { get; set; }
        public string codAnterior { get; set; }
        public double Sueldo { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public string nombreARD { get; set; }
        public string Abreviatura { get; set; }
        public decimal Riesgo { get; set; }
        public decimal Cargo { get; set; }
        public string Abreviatura2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miembros> Miembros { get; set; }
    }
}
