//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNovedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoNovedad()
        {
            this.NovedadPerdidaDocumento = new HashSet<NovedadPerdidaDocumento>();
            this.NovedadRepatriaciones = new HashSet<NovedadRepatriaciones>();
        }
    
        public int TipoNovedadID { get; set; }
        public string Nombre { get; set; }
        public int EstatusID { get; set; }
        public string Vista { get; set; }
        public int AuditoriaID { get; set; }
    
        public virtual Auditoria Auditoria { get; set; }
        public virtual Estatus Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NovedadPerdidaDocumento> NovedadPerdidaDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NovedadRepatriaciones> NovedadRepatriaciones { get; set; }
    }
}
