//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNovedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoNovedad()
        {
            this.NovedadPerdidaDocumento = new HashSet<NovedadPerdidaDocumento>();
            this.NovedadRepatriaciones = new HashSet<NovedadRepatriaciones>();
        }
    
        public int TipoNovedadID { get; set; }
        public string Nombre { get; set; }
        public int EstatusID { get; set; }
        public string Vista { get; set; }
        public int AuditoriaID { get; set; }
    
        public virtual Auditoria Auditoria { get; set; }
        public virtual Estatus Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NovedadPerdidaDocumento> NovedadPerdidaDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NovedadRepatriaciones> NovedadRepatriaciones { get; set; }
    }
}
