//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public int EstatusID { get; set; }
        public Nullable<int> InstitucionID { get; set; }
        public Nullable<bool> CambioClave { get; set; }
        public Nullable<int> AuditoriaID { get; set; }
        public Nullable<int> BrigadaID { get; set; }
        public int PerfilID { get; set; }
        public Nullable<int> RangoID { get; set; }
    }
}
